/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez;

/**
 *
 * @author angel
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_ReservarSede = new javax.swing.JButton();
        jB_IntroducirRes = new javax.swing.JButton();
        jB_Inscribirse = new javax.swing.JButton();
        jB_Historial = new javax.swing.JButton();
        jB_AsignarSede = new javax.swing.JButton();
        jB_AsignarResponsable = new javax.swing.JButton();
        jL_Admin = new javax.swing.JLabel();
        jL_Nombre = new javax.swing.JLabel();
        jTF_nombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB_ReservarSede.setText("Reservar Sede");
        jB_ReservarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ReservarSedeActionPerformed(evt);
            }
        });

        jB_IntroducirRes.setText("Introducir Resultado");

        jB_Inscribirse.setText("Incribirse Torneo");
        jB_Inscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_InscribirseActionPerformed(evt);
            }
        });

        jB_Historial.setText("Historial");
        jB_Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_HistorialActionPerformed(evt);
            }
        });

        jB_AsignarSede.setText("Asignar Sede");

        jB_AsignarResponsable.setText("Asignar Responsable a Menor");

        jL_Admin.setText("ADMINISTRACION");

        jL_Nombre.setText("nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_ReservarSede)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jB_Historial)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jB_IntroducirRes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Admin)
                            .addComponent(jB_AsignarSede))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jB_Inscribirse)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_AsignarResponsable)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jL_Admin)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Nombre)
                    .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Historial)
                    .addComponent(jB_AsignarSede)
                    .addComponent(jB_AsignarResponsable))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_ReservarSede)
                    .addComponent(jB_IntroducirRes)
                    .addComponent(jB_Inscribirse))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_ReservarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ReservarSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_ReservarSedeActionPerformed

    private void jB_HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_HistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_HistorialActionPerformed

    private void jB_InscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_InscribirseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_InscribirseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_AsignarResponsable;
    private javax.swing.JButton jB_AsignarSede;
    private javax.swing.JButton jB_Historial;
    private javax.swing.JButton jB_Inscribirse;
    private javax.swing.JButton jB_IntroducirRes;
    private javax.swing.JButton jB_ReservarSede;
    private javax.swing.JLabel jL_Admin;
    private javax.swing.JLabel jL_Nombre;
    private javax.swing.JTextField jTF_nombre;
    // End of variables declaration//GEN-END:variables
}
