/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez;

import Fachada.Fachada;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author angel
 */
public class IntroducirResultado extends javax.swing.JFrame {
    private JFrame pganterior;
    private Fachada usuario;    
    private DefaultListModel lista;
    /**
     * Creates new form Resultado
     */
    
    public IntroducirResultado(Fachada user,JFrame anterior) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = user;
        this.pganterior = anterior;
        this.lista = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Rival = new javax.swing.JLabel();
        jTF_rival = new javax.swing.JTextField();
        jL_Ganador = new javax.swing.JLabel();
        jTF_ganador = new javax.swing.JTextField();
        jL_Fecha = new javax.swing.JLabel();
        jL_TiempoPartida = new javax.swing.JLabel();
        jTF_Tiempo = new javax.swing.JTextField();
        jB_Salir = new javax.swing.JButton();
        jB_Introducir = new javax.swing.JButton();
        jL_Resultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_PartidasDisp = new javax.swing.JList<>();
        jDC_fecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jTF_dniJugador = new javax.swing.JTextField();
        jB_buscarTorneos = new javax.swing.JButton();
        jB_Seleccionar = new javax.swing.JButton();
        jB_verPartidas = new javax.swing.JButton();
        jCB_torneos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_Torneo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_Rival.setText("Rival");

        jTF_rival.setEditable(false);
        jTF_rival.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jL_Ganador.setText("Ganador");

        jL_Fecha.setText("Fecha");

        jL_TiempoPartida.setText("Tiempo Partida");

        jB_Salir.setText("Salir");
        jB_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SalirActionPerformed(evt);
            }
        });

        jB_Introducir.setText("Introducir");
        jB_Introducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_IntroducirActionPerformed(evt);
            }
        });

        jL_Resultado.setText("RESULTADO");

        jScrollPane1.setViewportView(jList_PartidasDisp);

        jLabel1.setText("DNI");

        jB_buscarTorneos.setText("Buscar Torneos");
        jB_buscarTorneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarTorneosActionPerformed(evt);
            }
        });

        jB_Seleccionar.setText("Seleccionar");
        jB_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SeleccionarActionPerformed(evt);
            }
        });

        jB_verPartidas.setText("Ver Partidas");
        jB_verPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_verPartidasActionPerformed(evt);
            }
        });

        jCB_torneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_torneosActionPerformed(evt);
            }
        });

        jLabel2.setText("Torneos:");

        jLabel3.setText("Torneo");

        jTF_Torneo.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB_Seleccionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jB_Salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_Introducir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_dniJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_buscarTorneos)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCB_torneos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jB_verPartidas))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_Torneo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL_Rival)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_rival, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jL_Resultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Fecha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_TiempoPartida, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_Ganador, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_Tiempo)
                            .addComponent(jTF_ganador)
                            .addComponent(jDC_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jL_Resultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_dniJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jB_buscarTorneos))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_verPartidas)
                            .addComponent(jCB_torneos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Seleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_rival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Rival)
                    .addComponent(jLabel3)
                    .addComponent(jTF_Torneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_ganador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Ganador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_Fecha)
                    .addComponent(jDC_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_TiempoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Salir)
                    .addComponent(jB_Introducir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_IntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_IntroducirActionPerformed
        String jugador, ganador, rival, tiempo, torneo;
        Date fecha;                
        
        jugador = jTF_dniJugador.getText();
        torneo = jTF_Torneo.getText();
        fecha = jDC_fecha.getDate();
        ganador = jTF_ganador.getText();
        rival = jTF_rival.getText();
        tiempo = jTF_Tiempo.getText();
        
        if(!usuario.introducirResultado(jugador,torneo, ganador, rival, fecha, tiempo)){
            JOptionPane.showMessageDialog(null, "Error al introducir el resultado", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Transaccion hecha correctamente.\n", "AVISO",JOptionPane.INFORMATION_MESSAGE);
            
            jTF_Torneo.setText("");
            jDC_fecha.setCalendar(null);
            jTF_ganador.setText("");
            jTF_rival.setText("");
            jTF_Tiempo.setText("");
            jCB_torneos.removeAllItems();
            lista.removeAllElements();
            
            
            
            /*ArrayList lista = new ArrayList();
            lista = administrador.getLiga().getTorneos();

            for(int i = 0; i<lista.size();i++){
                System.out.println("Torneo " + (i+1) + ": " + lista.get(i).toString());
            }*/
        }
    }//GEN-LAST:event_jB_IntroducirActionPerformed

    private void jB_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SalirActionPerformed
        pganterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jB_SalirActionPerformed

    private void jB_buscarTorneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarTorneosActionPerformed
        ArrayList torneos = new ArrayList();
                
        torneos = usuario.buscarTorneosJugador(jTF_dniJugador.getText());
        
        if(!torneos.isEmpty()){
            for(int i = 0; i<torneos.size();i++){
                jCB_torneos.addItem(torneos.get(i).toString());
            }
        }                
        else{
            JOptionPane.showMessageDialog(null,"No hay torneos iniciados", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jB_buscarTorneosActionPerformed

    private void jB_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SeleccionarActionPerformed
        if(jList_PartidasDisp.getSelectedIndex() != -1){
            int index= jList_PartidasDisp.getSelectedIndex();
            jTF_Torneo.setText(jCB_torneos.getSelectedItem().toString());
            //System.out.println(lista.getElementAt(index));
            jTF_rival.setText(lista.getElementAt(index).toString());
        }
        else
            JOptionPane.showMessageDialog(null,"No se ha seleccionado ninguna partida disponible", "AVISO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jB_SeleccionarActionPerformed

    private void jB_verPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_verPartidasActionPerformed
        ArrayList listaPartidas = new ArrayList();
                
        listaPartidas = usuario.verPartidas(jTF_dniJugador.getText(), jCB_torneos.getSelectedItem().toString());
        
        jList_PartidasDisp.clearSelection();

        if(!listaPartidas.isEmpty()){
            for(int i = 0; i < listaPartidas.size(); i++){
                lista.addElement(listaPartidas.get(i));                   
            }
        }                
        else{
            JOptionPane.showMessageDialog(null,"No hay torneos disponibles para este jugador", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        jList_PartidasDisp.setModel(lista);
    }//GEN-LAST:event_jB_verPartidasActionPerformed

    private void jCB_torneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_torneosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_torneosActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Introducir;
    private javax.swing.JButton jB_Salir;
    private javax.swing.JButton jB_Seleccionar;
    private javax.swing.JButton jB_buscarTorneos;
    private javax.swing.JButton jB_verPartidas;
    private javax.swing.JComboBox<String> jCB_torneos;
    private com.toedter.calendar.JDateChooser jDC_fecha;
    private javax.swing.JLabel jL_Fecha;
    private javax.swing.JLabel jL_Ganador;
    private javax.swing.JLabel jL_Resultado;
    private javax.swing.JLabel jL_Rival;
    private javax.swing.JLabel jL_TiempoPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList_PartidasDisp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_Tiempo;
    private javax.swing.JTextField jTF_Torneo;
    private javax.swing.JTextField jTF_dniJugador;
    private javax.swing.JTextField jTF_ganador;
    private javax.swing.JTextField jTF_rival;
    // End of variables declaration//GEN-END:variables
}
