/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez;

import Fachada.Fachada;
import javax.swing.JFrame;
import modelo.Administrador;

/**
 *
 * @author angel
 */
public class Registrar extends javax.swing.JFrame {
    private Fachada administrador;
    private JFrame paganterior;
    private RegistroJugador registroJugador;
    private RegistroFederacion registroFederacion;
    private RegistroEntrenador registroEntrenador;
    private RegistroGerente registroGerente;
    private RegistroClub registroClub;
    private RegistroTorneo registroTorneo;

    /**
     * Creates new form Registrar
     */
    public Registrar(Fachada admin, JFrame pgant) {
        initComponents();        
        this.setLocationRelativeTo(null);
        administrador = admin;
        paganterior = pgant;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jB_regClub = new javax.swing.JButton();
        jB_regFede = new javax.swing.JButton();
        jB_regEntrenador = new javax.swing.JButton();
        jB_regGerente = new javax.swing.JButton();
        jB_regJugador = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jB_regTorneo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRAR");

        jB_regClub.setText("Registrar Club");
        jB_regClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_regClubActionPerformed(evt);
            }
        });

        jB_regFede.setText("Registrar Federacion");
        jB_regFede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_regFedeActionPerformed(evt);
            }
        });

        jB_regEntrenador.setText("Registrar Entrenador");
        jB_regEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_regEntrenadorActionPerformed(evt);
            }
        });

        jB_regGerente.setText("Registrar Gerente");
        jB_regGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_regGerenteActionPerformed(evt);
            }
        });

        jB_regJugador.setText("RegistrarJugador");
        jB_regJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_regJugadorActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jB_regTorneo.setText("Registrar Torneo");
        jB_regTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_regTorneoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_regGerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_regTorneo)
                        .addGap(18, 18, 18)
                        .addComponent(jB_regJugador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_regClub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_regFede)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_regEntrenador)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_regGerente)
                    .addComponent(jB_regJugador)
                    .addComponent(jB_regTorneo))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_regClub)
                    .addComponent(jB_regFede)
                    .addComponent(jB_regEntrenador))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_regFedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_regFedeActionPerformed
        registroFederacion = new RegistroFederacion(administrador,this);
        this.setVisible(false);
        registroFederacion.setVisible(true);
    }//GEN-LAST:event_jB_regFedeActionPerformed

    private void jB_regJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_regJugadorActionPerformed
        registroJugador = new RegistroJugador(administrador, this);        
        this.setVisible(false);
        registroJugador.setVisible(true);
    }//GEN-LAST:event_jB_regJugadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        paganterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB_regEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_regEntrenadorActionPerformed
        registroEntrenador = new RegistroEntrenador(administrador, this);        
        this.setVisible(false);
        registroEntrenador.setVisible(true);
    }//GEN-LAST:event_jB_regEntrenadorActionPerformed

    private void jB_regGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_regGerenteActionPerformed
        registroGerente = new RegistroGerente(administrador, this);        
        this.setVisible(false);
        registroGerente.setVisible(true);
    }//GEN-LAST:event_jB_regGerenteActionPerformed

    private void jB_regClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_regClubActionPerformed
        registroClub = new RegistroClub(administrador, this);        
        this.setVisible(false);
        registroClub.setVisible(true);
    }//GEN-LAST:event_jB_regClubActionPerformed

    private void jB_regTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_regTorneoActionPerformed
        registroTorneo = new RegistroTorneo(administrador, this);        
        this.setVisible(false);        
        registroTorneo.setVisible(true);
    }//GEN-LAST:event_jB_regTorneoActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_regClub;
    private javax.swing.JButton jB_regEntrenador;
    private javax.swing.JButton jB_regFede;
    private javax.swing.JButton jB_regGerente;
    private javax.swing.JButton jB_regJugador;
    private javax.swing.JButton jB_regTorneo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
